version: '3.8'
services:

  #
  # Application
  #

  app:
    build:
      context: src
      dockerfile: Dockerfile
    image: api
    command: sh -c "npm i && npm run start:debug"
    ports:
      - '${API_PORT_EXT:-3001}:3001'
      - '${API_PORT_DEBUG:-9229}:9229'
    environment:
      - DEBUG_PORT=9229
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  #
  # Services
  #

  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '${REDIS_PORT_EXT:-6379}:6379'
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT_EXT:-5432}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    external: true
  redis_data:
    external: true
